---
documentclass: jss
author:
  - name: FirstName LastName
    affiliation: University/Company
    address: >
      First line
      Second line
    email: \email{name@company.com}
    url: https://github.com/mages/ChainLadder
  - name: Second Author
    affiliation: Affiliation
title:
  formatted: "Claims reserving with R: \\pkg{ChainLadder}"
  # If you use tex in the formatted title, also supply version without
  plain:     "Claims reserving with R: ChainLadder"
  # For running headers, if needed
  short:     "Claims reserving with R: \\pkg{ChainLadder}"
abstract: >
  The ChainLadder package provides various statistical methods
  which are typically used for the estimation of outstanding claims reserves
  in general insurance, including those to estimate the claims development
  results as required under Solvency II.
keywords:
  # at least one keyword must be supplied
  formatted: [reserving, non-life insurance, "\\proglang{R}"]
  plain:     [reserving, non-life insurance, R]
preamble: >
  \usepackage{amsmath}
output: rticles::jss_article
---

\pagebreak

# Introduction

\pagebreak

# Package Overview
## Existing tools
## Our Package

\pagebreak

# Support functions for data manipulation
## Working with triangles
### Creating triangles interactively
### Converting data into triangles
### Visualizing triangles
### Integration with Excel

\pagebreak

# ChainLadder: Models and Methods
## Classic chain-ladder methods
### Mack chain-ladder
### BootChainLadder
## Growth curves
### Clark LDF
## Modelling paid and incurred data
### MunichChainLadder
### Paid-incurred chain model
## Multivariate chain-ladder
## GLMs
### Tweedie model

\pagebreak

# Solvency II: Claims Development Result
## CDR function

\pagebreak

# Support functions for data manipulation and model validation
## Interpreting graphical outputs
## Model validation with tweedieReserve

\pagebreak

# Conclusion

\pagebreak
