<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"><title>Calculate Age-to-Age Factors — ata • ChainLadder</title><!-- favicons --><link rel="icon" type="image/png" sizes="96x96" href="../favicon-96x96.png"><link rel="icon" type="”image/svg+xml”" href="../favicon.svg"><link rel="apple-touch-icon" sizes="180x180" href="../apple-touch-icon.png"><link rel="icon" sizes="any" href="../favicon.ico"><link rel="manifest" href="../site.webmanifest"><script src="../deps/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"><link href="../deps/bootstrap-5.3.1/bootstrap.min.css" rel="stylesheet"><script src="../deps/bootstrap-5.3.1/bootstrap.bundle.min.js"></script><link href="../deps/font-awesome-6.5.2/css/all.min.css" rel="stylesheet"><link href="../deps/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet"><script src="../deps/headroom-0.11.0/headroom.min.js"></script><script src="../deps/headroom-0.11.0/jQuery.headroom.min.js"></script><script src="../deps/bootstrap-toc-1.0.1/bootstrap-toc.min.js"></script><script src="../deps/clipboard.js-2.0.11/clipboard.min.js"></script><script src="../deps/search-1.0.0/autocomplete.jquery.min.js"></script><script src="../deps/search-1.0.0/fuse.min.js"></script><script src="../deps/search-1.0.0/mark.min.js"></script><!-- pkgdown --><script src="../pkgdown.js"></script><meta property="og:title" content="Calculate Age-to-Age Factors — ata"><meta name="description" content='Calculate the matrix of age-to-age factors
(also called "report-to-report" factors, or "link ratios")
for an object of class triangle.'><meta property="og:description" content='Calculate the matrix of age-to-age factors
(also called "report-to-report" factors, or "link ratios")
for an object of class triangle.'><meta property="og:image" content="http://mages.github.io/ChainLadder/logo.png"></head><body>
    <a href="#main" class="visually-hidden-focusable">Skip to contents</a>


    <nav class="navbar navbar-expand-lg fixed-top bg-light" data-bs-theme="light" aria-label="Site navigation"><div class="container">

    <a class="navbar-brand me-2" href="../index.html">ChainLadder</a>

    <small class="nav-text text-muted me-auto" data-bs-toggle="tooltip" data-bs-placement="bottom" title="">0.2.21</small>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navbar" class="collapse navbar-collapse ms-3">
      <ul class="navbar-nav me-auto"><li class="nav-item"><a class="nav-link" href="../articles/ChainLadder.html">Get started</a></li>
<li class="active nav-item"><a class="nav-link" href="../reference/index.html">Reference</a></li>
<li class="nav-item"><a class="nav-link" href="../news/index.html">Changelog</a></li>
      </ul><ul class="navbar-nav"><li class="nav-item"><form class="form-inline" role="search">
 <input class="form-control" type="search" name="search-input" id="search-input" autocomplete="off" aria-label="Search site" placeholder="Search for" data-search-index="../search.json"></form></li>
<li class="nav-item"><a class="external-link nav-link" href="https://github.com/mages/ChainLadder/" aria-label="GitHub"><span class="fa fab fa-github fa-lg"></span></a></li>
      </ul></div>


  </div>
</nav><div class="container template-reference-topic">
<div class="row">
  <main id="main" class="col-md-9"><div class="page-header">
      <img src="../logo.png" class="logo" alt=""><h1>Calculate Age-to-Age Factors</h1>

      <div class="d-none name"><code>ata.rd</code></div>
    </div>

    <div class="ref-description section level2">
    <p>Calculate the matrix of age-to-age factors
(also called "report-to-report" factors, or "link ratios")
for an object of class <code>triangle</code>.</p>
    </div>

    <div class="section level2">
    <h2 id="ref-usage">Usage<a class="anchor" aria-label="anchor" href="#ref-usage"></a></h2>
    <div class="sourceCode"><pre class="sourceCode r"><code><span><span class="fu">ata</span><span class="op">(</span><span class="va">Triangle</span>, NArow.rm <span class="op">=</span> <span class="cn">TRUE</span>, colname.sep <span class="op">=</span> <span class="st">"-"</span>,</span>
<span>        colname.order<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="st">"ascending"</span>,<span class="st">"descending"</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
    </div>

    <div class="section level2">
    <h2 id="arguments">Arguments<a class="anchor" aria-label="anchor" href="#arguments"></a></h2>
    <p></p>
<dl><dt id="arg-triangle">Triangle<a class="anchor" aria-label="anchor" href="#arg-triangle"></a></dt>
<dd><p>a loss "triangle". Must be a <code>matrix</code>.</p></dd>

    <dt id="arg-narow-rm">NArow.rm<a class="anchor" aria-label="anchor" href="#arg-narow-rm"></a></dt>
<dd><p><code>logical</code> indicating if
        rows of age-to-age (ata) factors that are all <code>NA</code>
        should be removed.
        "All-NA" rows typically occur for the most recent origin year
        of a loss triangle.</p></dd>

    <dt id="arg-colname-sep">colname.sep<a class="anchor" aria-label="anchor" href="#arg-colname-sep"></a></dt>
<dd><p>a <code>character</code> indicating the separator
        character to place between the column names of <code>Triangle</code>
        that will be used to lable the columns of the resulting
        matrix of ata factors</p></dd>

    <dt id="arg-colname-order">colname.order<a class="anchor" aria-label="anchor" href="#arg-colname-order"></a></dt>
<dd><p>"ascending" indicates that the less mature
        age comes first in the column labels of the ata matrix</p></dd>

    </dl></div>
    <div class="section level2">
    <h2 id="details">Details<a class="anchor" aria-label="anchor" href="#details"></a></h2>
    <p><code>ata</code> constructs a matrix of age-to-age (ata) factors resulting
from a loss "triangle" or a <code>matrix</code>.
Simple averages and volume weighted averages are saved as
"smpl" and "vwtd" attributes, respectively.</p>
    </div>
    <div class="section level2">
    <h2 id="value">Value<a class="anchor" aria-label="anchor" href="#value"></a></h2>
    <p>A <code>matrix</code> with "smpl" and "vwtd" attributes.</p>
    </div>
    <div class="section level2">
    <h2 id="author">Author<a class="anchor" aria-label="anchor" href="#author"></a></h2>
    <p>Daniel Murphy</p>
    </div>
    <div class="section level2">
    <h2 id="see-also">See also<a class="anchor" aria-label="anchor" href="#see-also"></a></h2>
    <div class="dont-index"><p><code><a href="summary.ata.html">summary.ata</a></code>, <code><a href="print.ata.html">print.ata</a></code> and <code><a href="chainladder.html">chainladder</a></code></p></div>
    </div>

    <div class="section level2">
    <h2 id="ref-examples">Examples<a class="anchor" aria-label="anchor" href="#ref-examples"></a></h2>
    <div class="sourceCode"><pre class="sourceCode r"><code><span class="r-in"><span><span class="fu">ata</span><span class="op">(</span><span class="va">GenIns</span><span class="op">)</span></span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span>       dev</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> origin   1-2   2-3   3-4   4-5   5-6   6-7   7-8   8-9  9-10</span>
<span class="r-out co"><span class="r-pr">#&gt;</span>   1    3.143 1.543 1.278 1.238 1.209 1.044 1.040 1.063 1.018</span>
<span class="r-out co"><span class="r-pr">#&gt;</span>   2    3.511 1.755 1.545 1.133 1.084 1.128 1.057 1.086    NA</span>
<span class="r-out co"><span class="r-pr">#&gt;</span>   3    4.448 1.717 1.458 1.232 1.037 1.120 1.061    NA    NA</span>
<span class="r-out co"><span class="r-pr">#&gt;</span>   4    4.568 1.547 1.712 1.073 1.087 1.047    NA    NA    NA</span>
<span class="r-out co"><span class="r-pr">#&gt;</span>   5    2.564 1.873 1.362 1.174 1.138    NA    NA    NA    NA</span>
<span class="r-out co"><span class="r-pr">#&gt;</span>   6    3.366 1.636 1.369 1.236    NA    NA    NA    NA    NA</span>
<span class="r-out co"><span class="r-pr">#&gt;</span>   7    2.923 1.878 1.439    NA    NA    NA    NA    NA    NA</span>
<span class="r-out co"><span class="r-pr">#&gt;</span>   8    3.953 2.016    NA    NA    NA    NA    NA    NA    NA</span>
<span class="r-out co"><span class="r-pr">#&gt;</span>   9    3.619    NA    NA    NA    NA    NA    NA    NA    NA</span>
<span class="r-out co"><span class="r-pr">#&gt;</span>   smpl 3.566 1.746 1.452 1.181 1.111 1.085 1.053 1.075 1.018</span>
<span class="r-out co"><span class="r-pr">#&gt;</span>   vwtd 3.491 1.747 1.457 1.174 1.104 1.086 1.054 1.077 1.018</span>
<span class="r-in"><span></span></span>
<span class="r-in"><span><span class="co"># Volume weighted average age-to-age factor of the "RAA" data</span></span></span>
<span class="r-in"><span><span class="va">y</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/attr.html" class="external-link">attr</a></span><span class="op">(</span><span class="fu">ata</span><span class="op">(</span><span class="va">RAA</span><span class="op">)</span>, <span class="st">"vwtd"</span><span class="op">)</span></span></span>
<span class="r-in"><span><span class="va">y</span></span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span>      1-2      2-3      3-4      4-5      5-6      6-7      7-8      8-9 </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> 2.999359 1.623523 1.270888 1.171675 1.113385 1.041935 1.033264 1.016936 </span>
<span class="r-out co"><span class="r-pr">#&gt;</span>     9-10 </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> 1.009217 </span>
<span class="r-in"><span><span class="co"># "To ultimate" factors with a 10% tail</span></span></span>
<span class="r-in"><span><span class="va">y</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/rev.html" class="external-link">rev</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/cumsum.html" class="external-link">cumprod</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rev.html" class="external-link">rev</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="va">y</span>, <span class="fl">1.1</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></span>
<span class="r-in"><span><span class="fu"><a href="https://rdrr.io/r/base/names.html" class="external-link">names</a></span><span class="op">(</span><span class="va">y</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html" class="external-link">paste</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html" class="external-link">colnames</a></span><span class="op">(</span><span class="va">RAA</span><span class="op">)</span>, <span class="st">"Ult"</span>, sep<span class="op">=</span><span class="st">"-"</span><span class="op">)</span></span></span>
<span class="r-in"><span><span class="va">y</span></span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span>    1-Ult    2-Ult    3-Ult    4-Ult    5-Ult    6-Ult    7-Ult    8-Ult </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> 9.812257 3.271452 2.015033 1.585531 1.353218 1.215409 1.166493 1.128940 </span>
<span class="r-out co"><span class="r-pr">#&gt;</span>    9-Ult   10-Ult </span>
<span class="r-out co"><span class="r-pr">#&gt;</span> 1.110138 1.100000 </span>
<span class="r-in"><span></span></span>
<span class="r-in"><span><span class="co">## Label the development columns in "ratio-type" format</span></span></span>
<span class="r-in"><span><span class="fu">ata</span><span class="op">(</span><span class="va">RAA</span>, colname.sep<span class="op">=</span><span class="st">":"</span>, colname.order<span class="op">=</span><span class="st">"desc"</span><span class="op">)</span></span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span>       dev</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> origin    2:1   3:2   4:3   5:4   6:5   7:6   8:7   9:8  10:9</span>
<span class="r-out co"><span class="r-pr">#&gt;</span>   1981  1.650 1.319 1.082 1.147 1.195 1.113 1.033 1.003 1.009</span>
<span class="r-out co"><span class="r-pr">#&gt;</span>   1982 40.425 1.259 1.977 1.292 1.132 0.993 1.043 1.033    NA</span>
<span class="r-out co"><span class="r-pr">#&gt;</span>   1983  2.637 1.543 1.163 1.161 1.186 1.029 1.026    NA    NA</span>
<span class="r-out co"><span class="r-pr">#&gt;</span>   1984  2.043 1.364 1.349 1.102 1.113 1.038    NA    NA    NA</span>
<span class="r-out co"><span class="r-pr">#&gt;</span>   1985  8.759 1.656 1.400 1.171 1.009    NA    NA    NA    NA</span>
<span class="r-out co"><span class="r-pr">#&gt;</span>   1986  4.260 1.816 1.105 1.226    NA    NA    NA    NA    NA</span>
<span class="r-out co"><span class="r-pr">#&gt;</span>   1987  7.217 2.723 1.125    NA    NA    NA    NA    NA    NA</span>
<span class="r-out co"><span class="r-pr">#&gt;</span>   1988  5.142 1.887    NA    NA    NA    NA    NA    NA    NA</span>
<span class="r-out co"><span class="r-pr">#&gt;</span>   1989  1.722    NA    NA    NA    NA    NA    NA    NA    NA</span>
<span class="r-out co"><span class="r-pr">#&gt;</span>   smpl  8.206 1.696 1.315 1.183 1.127 1.043 1.034 1.018 1.009</span>
<span class="r-out co"><span class="r-pr">#&gt;</span>   vwtd  2.999 1.624 1.271 1.172 1.113 1.042 1.033 1.017 1.009</span>
<span class="r-in"><span></span></span>
</code></pre></div>
    </div>
  </main><aside class="col-md-3"><nav id="toc" aria-label="Table of contents"><h2>On this page</h2>
    </nav></aside></div>


    <footer><div class="pkgdown-footer-left">
  <p>Developed by Markus Gesmann, Daniel Murphy, Yanwei (Wayne) Zhang, Alessandro Carrato, Mario Wuthrich, Fabio Concina, Eric Dal Moro.</p>
</div>

<div class="pkgdown-footer-right">
  <p>Site built with <a href="https://pkgdown.r-lib.org/" class="external-link">pkgdown</a> 2.2.0.</p>
</div>

    </footer></div>





  </body></html>

