<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"><title>Summary methods for Clark objects — summary.clark • ChainLadder</title><!-- favicons --><link rel="icon" type="image/png" sizes="96x96" href="../favicon-96x96.png"><link rel="icon" type="”image/svg+xml”" href="../favicon.svg"><link rel="apple-touch-icon" sizes="180x180" href="../apple-touch-icon.png"><link rel="icon" sizes="any" href="../favicon.ico"><link rel="manifest" href="../site.webmanifest"><script src="../deps/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"><link href="../deps/bootstrap-5.3.1/bootstrap.min.css" rel="stylesheet"><script src="../deps/bootstrap-5.3.1/bootstrap.bundle.min.js"></script><link href="../deps/font-awesome-6.5.2/css/all.min.css" rel="stylesheet"><link href="../deps/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet"><script src="../deps/headroom-0.11.0/headroom.min.js"></script><script src="../deps/headroom-0.11.0/jQuery.headroom.min.js"></script><script src="../deps/bootstrap-toc-1.0.1/bootstrap-toc.min.js"></script><script src="../deps/clipboard.js-2.0.11/clipboard.min.js"></script><script src="../deps/search-1.0.0/autocomplete.jquery.min.js"></script><script src="../deps/search-1.0.0/fuse.min.js"></script><script src="../deps/search-1.0.0/mark.min.js"></script><!-- pkgdown --><script src="../pkgdown.js"></script><meta property="og:title" content="Summary methods for Clark objects — summary.clark"><meta name="description" content="summary
  methods for ClarkLDF and ClarkCapeCod objects"><meta property="og:description" content="summary
  methods for ClarkLDF and ClarkCapeCod objects"><meta property="og:image" content="http://mages.github.io/ChainLadder/logo.png"></head><body>
    <a href="#main" class="visually-hidden-focusable">Skip to contents</a>


    <nav class="navbar navbar-expand-lg fixed-top bg-light" data-bs-theme="light" aria-label="Site navigation"><div class="container">

    <a class="navbar-brand me-2" href="../index.html">ChainLadder</a>

    <small class="nav-text text-muted me-auto" data-bs-toggle="tooltip" data-bs-placement="bottom" title="">0.2.20</small>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navbar" class="collapse navbar-collapse ms-3">
      <ul class="navbar-nav me-auto"><li class="nav-item"><a class="nav-link" href="../articles/ChainLadder.html">Get started</a></li>
<li class="active nav-item"><a class="nav-link" href="../reference/index.html">Reference</a></li>
<li class="nav-item"><a class="nav-link" href="../news/index.html">Changelog</a></li>
      </ul><ul class="navbar-nav"><li class="nav-item"><form class="form-inline" role="search">
 <input class="form-control" type="search" name="search-input" id="search-input" autocomplete="off" aria-label="Search site" placeholder="Search for" data-search-index="../search.json"></form></li>
<li class="nav-item"><a class="external-link nav-link" href="https://github.com/mages/ChainLadder/" aria-label="GitHub"><span class="fa fab fa-github fa-lg"></span></a></li>
      </ul></div>


  </div>
</nav><div class="container template-reference-topic">
<div class="row">
  <main id="main" class="col-md-9"><div class="page-header">
      <img src="../logo.png" class="logo" alt=""><h1>Summary methods for Clark objects</h1>

      <div class="d-none name"><code>summary.clark.rd</code></div>
    </div>

    <div class="ref-description section level2">
    <p><code>summary</code>
  methods for <code>ClarkLDF</code> and <code>ClarkCapeCod</code> objects</p>
    </div>

    <div class="section level2">
    <h2 id="ref-usage">Usage<a class="anchor" aria-label="anchor" href="#ref-usage"></a></h2>
    <div class="sourceCode"><pre class="sourceCode r"><code><span><span class="co"># S3 method for class 'ClarkLDF'</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html" class="external-link">summary</a></span><span class="op">(</span><span class="va">object</span>, <span class="va">...</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># S3 method for class 'ClarkCapeCod'</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html" class="external-link">summary</a></span><span class="op">(</span><span class="va">object</span>, <span class="va">...</span><span class="op">)</span></span></code></pre></div>
    </div>

    <div class="section level2">
    <h2 id="arguments">Arguments<a class="anchor" aria-label="anchor" href="#arguments"></a></h2>
    <p></p>
<dl><dt id="arg-object">object<a class="anchor" aria-label="anchor" href="#arg-object"></a></dt>
<dd><p>object resulting from a run of the <code><a href="ClarkLDF.html">ClarkLDF</a></code>
        or <code><a href="ClarkCapeCod.html">ClarkCapeCod</a></code> functions.</p></dd>

    <dt id="arg--">...<a class="anchor" aria-label="anchor" href="#arg--"></a></dt>
<dd><p>not currently used</p></dd>

</dl></div>
    <div class="section level2">
    <h2 id="details">Details<a class="anchor" aria-label="anchor" href="#details"></a></h2>
    <p><code>summary.ClarkLDF</code> returns a <code>data.frame</code> that holds the columns of a
typical "Development-type" exhibit.</p>
<p><code>summary.ClarkCapeCod</code> returns a <code>data.frame</code> that holds the columns of a
typical "Bornhuetter-Ferguson-type" exhibit.</p>
    </div>
    <div class="section level2">
    <h2 id="value">Value<a class="anchor" aria-label="anchor" href="#value"></a></h2>
    <p><code>summary.ClarkLDF</code> and <code>summary.ClarkCapeCod</code> return
        <code>data.frame</code>s whose columns are objects of the appropriate <code>mode</code>
        (i.e., <code>character</code> for "Origin", otherwise <code>numeric</code>)</p>
    </div>
    <div class="section level2">
    <h2 id="author">Author<a class="anchor" aria-label="anchor" href="#author"></a></h2>
    <p>Dan Murphy</p>
    </div>
    <div class="section level2">
    <h2 id="see-also">See also<a class="anchor" aria-label="anchor" href="#see-also"></a></h2>
    <div class="dont-index"><p>See also <code><a href="ClarkLDF.html">ClarkLDF</a></code></p></div>
    </div>

    <div class="section level2">
    <h2 id="ref-examples">Examples<a class="anchor" aria-label="anchor" href="#ref-examples"></a></h2>
    <div class="sourceCode"><pre class="sourceCode r"><code><span class="r-in"><span><span class="va">y</span> <span class="op">&lt;-</span> <span class="fu"><a href="ClarkLDF.html">ClarkLDF</a></span><span class="op">(</span><span class="va">RAA</span><span class="op">)</span></span></span>
<span class="r-in"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html" class="external-link">summary</a></span><span class="op">(</span><span class="va">y</span><span class="op">)</span></span></span>
<span class="r-out co"><span class="r-pr">#&gt;</span>       Origin CurrentValue       Ldf UltimateValue FutureValue  StdError</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> 1981    1981        18834  1.216225      22906.38    4072.382  2792.102</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> 1982    1982        16704  1.251157      20899.33    4195.330  2832.930</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> 1983    1983        23466  1.297259      30441.49    6975.487  4050.197</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> 1984    1984        27067  1.360425      36822.61    9755.612  5146.615</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> 1985    1985        26180  1.451336      37995.98   11815.980  5858.178</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> 1986    1986        15852  1.591348      25226.05    9374.053  4877.406</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> 1987    1987        12314  1.829470      22528.09   10214.094  5206.183</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> 1988    1988        13112  2.304832      30220.96   17108.955  7567.747</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> 1989    1989         5395  3.595747      19399.06   14004.057  7506.058</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> 1990    1990         2063 12.394139      25569.11   23506.109 17226.577</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> Total  Total       160987        NA     272009.06  111022.060 36101.662</span>
<span class="r-out co"><span class="r-pr">#&gt;</span>              CV</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> 1981  0.6856189</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> 1982  0.6752578</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> 1983  0.5806329</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> 1984  0.5275543</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> 1985  0.4957844</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> 1986  0.5203092</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> 1987  0.5097058</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> 1988  0.4423267</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> 1989  0.5359916</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> 1990  0.7328553</span>
<span class="r-out co"><span class="r-pr">#&gt;</span> Total 0.3251756</span>
<span class="r-in"><span></span></span>
</code></pre></div>
    </div>
  </main><aside class="col-md-3"><nav id="toc" aria-label="Table of contents"><h2>On this page</h2>
    </nav></aside></div>


    <footer><div class="pkgdown-footer-left">
  <p>Developed by Markus Gesmann, Daniel Murphy, Yanwei (Wayne) Zhang, Alessandro Carrato, Mario Wuthrich, Fabio Concina, Eric Dal Moro.</p>
</div>

<div class="pkgdown-footer-right">
  <p>Site built with <a href="https://pkgdown.r-lib.org/" class="external-link">pkgdown</a> 2.2.0.</p>
</div>

    </footer></div>





  </body></html>

